#!/bin/bash -e
ABS_PATH="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
SCRIPT_DIR="$(dirname ${ABS_PATH})"
ACTOOL=/usr/share/rkt/bin/actool

if [[ -z $1 ]]; then
    echo Please provide the ACI source directory, relative to the build script.
    echo Usage: ./build hello_go
    exit 1
fi

SRCDIR=${SCRIPT_DIR}/${1}
NAME="$(basename ${SRCDIR})"
TMPDIR=${SCRIPT_DIR}/.tmp/${NAME}
OUTDIR=$PWD/out

[[ -d ${TMPDIR} ]] && rm -Rf "${TMPDIR}"
mkdir -p ${TMPDIR} ${OUTDIR}
pushd ${SRCDIR}
${ACTOOL} -debug validate manifest.json
cp manifest.json ${TMPDIR}/manifest
./build "${TMPDIR}"
popd
tree -a ${TMPDIR}
${ACTOOL} -debug build --overwrite ${TMPDIR} ${OUTDIR}/${NAME}.aci 
[[ ! -e ${OUTDIR}/${NAME}.aci.asc ]] || rm ${OUTDIR}/${NAME}.aci.asc 
gpg --batch --armor --output ${OUTDIR}/${NAME}.aci.asc --detach-sig ${OUTDIR}/${NAME}.aci
rm -Rf ${TMPDIR}
